### ISSUE TITLE
Chapter annotation - url of project.json needs to be changed

### ISSUE THREAD

**Issue by pulkitmehtawork** [GokuMohandas/applied-ml#5]
Hello Team  , 
1. Url of project.json in annotation chapter needs to be changed from 
https://raw.githubusercontent.com/madewithml/datasets/main/projects.json
to 
https://raw.githubusercontent.com/GokuMohandas/applied-ml/main/datasets/projects.json

2. url of auxillary data also needs to be changed from 
https://raw.githubusercontent.com/madewithml/datasets/main/tags.json
to 
https://github.com/GokuMohandas/applied-ml/blob/main/datasets/tags.json

Please update the same .

**Comment by GokuMohandas** [comment]
Good catch @pulkitmehtawork, I'll push the fixes along with the new lessons next week.
